name: Add opportunity
description: Add a new opportunity to eosguidehub
title: "Add: "
labels: ["opportunity", "publish-opportunity"]
body:
  - type: input
    id: public_title
    attributes:
      label: Opportunity title (shows on site)
      placeholder: "Example: Westlake Financial Services illegal fees settlement"
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        **Card link behavior**
        - The homepage card should link to your internal article page.
        - Put the article slug below. Example: `prg-breach-settlement` links to `/articles/prg-breach-settlement.html`.
        - Add the official settlement URLs in the fields farther down. The article should link out to the official site.

  - type: input
    id: article_slug
    attributes:
      label: Article slug (links to your article)
      description: "Match the published article filename without .html. Example: prg-breach-settlement"
      placeholder: "prg-breach-settlement"
    validations:
      required: true


  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Class Action
        - Rebates
        - Government
        - Other
    validations:
      required: true

  - type: input
    id: state
    attributes:
      label: State
      placeholder: "Nationwide or Colorado or CA"
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: Deadline (YYYY-MM-DD)
      placeholder: "2026-03-15"
    validations:
      required: false

  - type: input
    id: amount
    attributes:
      label: Amount
      placeholder: "$50–$200"
    validations:
      required: false

  - type: input
    id: details_url
    attributes:
      label: Details URL (info page)
      placeholder: "https://..."
    validations:
      required: true

  - type: input
    id: apply_url
    attributes:
      label: Apply URL (where user files claim)
      placeholder: "https://..."
    validations:
      required: false

  - type: textarea
    id: card_description
    attributes:
      label: Card description (shows on site)
      placeholder: "2–4 short sentences in your own words."
    validations:
      required: true

  - type: textarea
    id: source_text
    attributes:
      label: Source text (optional fallback)
      description: "Paste key lines from the details page if it blocks bots. Eligibility, deadline, proof, payout, how to file."
      placeholder: "Paste key lines here (not required if URL fetch works)."
    validations:
      required: false

  - type: checkboxes
    id: featured
    attributes:
      label: Featured
      options:
        - label: Mark as featured
          required: false
