name: New Article
description: Publish a new settlement or refund guide to eosguidehub.com
title: "[Article] "
labels: ["article"]

body:

  - type: input
    id: title
    attributes:
      label: Article title
      description: "Full headline shown at the top of the article."
      placeholder: "Company Name Settlement – File a Claim by [Deadline]"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: URL slug
      description: "Short and URL-friendly. Use hyphens."
      placeholder: "company-settlement-2026"
    validations:
      required: true

  - type: textarea
    id: blurb
    attributes:
      label: Short blurb (for article intro and listing page)
      description: "1–2 sentences. This helps SEO and appears on the articles list."
      placeholder: "Eligible people may receive compensation if they... Deadline is..."
    validations:
      required: true

  - type: input
    id: last_updated
    attributes:
      label: Last updated
      description: "Date this article was written or reviewed."
      placeholder: "February 20, 2026"
    validations:
      required: true

  - type: textarea
    id: eligible_states
    attributes:
      label: Eligible states / location
      description: "Type 'Nationwide' or list full state names separated by commas."
      placeholder: "Nationwide\n\nor\n\nCalifornia, Illinois, New York"
    validations:
      required: true

  - type: input
    id: official_website
    attributes:
      label: Official settlement website
      description: "Primary official URL where users file claims."
      placeholder: "https://www.example-settlement.com/"
    validations:
      required: true

  - type: input
    id: hero_image
    attributes:
      label: Hero image URL (optional)
      description: "Leave blank if not available."
      placeholder: "https://eosguidehub.com/assets/articles/example.jpg"
    validations:
      required: false

  - type: input
    id: hero_credit
    attributes:
      label: Hero image credit (optional)
      placeholder: "Photo credit: Example Source"
    validations:
      required: false

  - type: input
    id: deadline
    attributes:
      label: Claim deadline (optional)
      placeholder: "April 10, 2026"
    validations:
      required: false

  - type: input
    id: optout_deadline
    attributes:
      label: Opt-out deadline (optional)
      placeholder: "March 1, 2026"
    validations:
      required: false

  - type: input
    id: hearing_date
    attributes:
      label: Final approval hearing (optional)
      placeholder: "May 12, 2026"
    validations:
      required: false

  - type: input
    id: settlement_amount
    attributes:
      label: Total settlement fund (optional)
      placeholder: "$10,000,000"
    validations:
      required: false

  - type: input
    id: max_payment
    attributes:
      label: Maximum payment per person (optional)
      placeholder: "Up to $5,000"
    validations:
      required: false

  - type: input
    id: nodoc_payment
    attributes:
      label: No-document payment amount (optional)
      placeholder: "$25 without documentation"
    validations:
      required: false

  - type: input
    id: ca_payment
    attributes:
      label: California-specific payment (optional)
      placeholder: "$100 for California residents"
    validations:
      required: false

  - type: input
    id: credit_monitoring
    attributes:
      label: Credit monitoring benefit (optional)
      placeholder: "2 years of credit monitoring"
    validations:
      required: false

  - type: textarea
    id: article_body
    attributes:
      label: Main article body (optional)
      description: "Write in short sections. Markdown headings supported."
      placeholder: |
        ## What happened
        ...

        ## Who may qualify
        ...
    validations:
      required: false

  - type: textarea
    id: eligibility
    attributes:
      label: Eligibility checklist (optional)
      description: "One item per line."
      placeholder: |
        Received a notice OR meet official criteria
        Lived in the U.S. during the class period
    validations:
      required: false

  - type: textarea
    id: how_to_file
    attributes:
      label: How to file (steps, optional)
      description: "One step per line."
      placeholder: |
        Go to the official site
        Click 'Submit Claim'
        Complete the form
    validations:
      required: false

  - type: textarea
    id: faqs
    attributes:
      label: FAQs (optional)
      description: "Format like Q: ... then A: ..."
      placeholder: |
        Q: Who qualifies?
        A: ...

        Q: What proof is required?
        A: ...
    validations:
      required: false

  - type: input
    id: admin_phone
    attributes:
      label: Administrator phone (optional)
      placeholder: "1-800-555-1234"
    validations:
      required: false

  - type: input
    id: admin_email
    attributes:
      label: Administrator email (optional)
      placeholder: "info@example-settlement.com"
    validations:
      required: false

  - type: input
    id: attorney_fees
    attributes:
      label: Attorney fees (optional)
      placeholder: "Up to $X"
    validations:
      required: false

  - type: input
    id: service_awards
    attributes:
      label: Service awards (optional)
      placeholder: "Up to $X"
    validations:
      required: false
