name: New Article
description: Publish a new settlement or refund guide to eosguidehub.com
title: "[Article] "
labels: ["article"]

body:
  - type: input
    id: title
    attributes:
      label: Article title
      description: "Full headline shown at the top of the article."
      placeholder: "Company Name Settlement – File a Claim by [Deadline]"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: URL slug
      description: "Short and URL-friendly. Use hyphens."
      placeholder: "panda-restaurant-group-data-breach-settlement"
    validations:
      required: true

  - type: textarea
    id: blurb
    attributes:
      label: "Short blurb (for the /articles list + article intro)"
      description: "1–2 sentences. This is your quick summary and helps SEO."
      placeholder: "Eligible people may get up to $X if they... Deadline is..."
    validations:
      required: true

  - type: input
    id: last_updated
    attributes:
      label: Last updated
      description: "Date this article was written or last reviewed."
      placeholder: "February 19, 2026"
    validations:
      required: true

  - type: dropdown
    id: eligible_states
    attributes:
      label: Eligible states
      description: "Pick Nationwide or the states this applies to. Full state names."
      multiple: true
      options:
        - Nationwide
        - Alabama
        - Alaska
        - Arizona
        - Arkansas
        - California
        - Colorado
        - Connecticut
        - Delaware
        - Florida
        - Georgia
        - Hawaii
        - Idaho
        - Illinois
        - Indiana
        - Iowa
        - Kansas
        - Kentucky
        - Louisiana
        - Maine
        - Maryland
        - Massachusetts
        - Michigan
        - Minnesota
        - Mississippi
        - Missouri
        - Montana
        - Nebraska
        - Nevada
        - New Hampshire
        - New Jersey
        - New Mexico
        - New York
        - North Carolina
        - North Dakota
        - Ohio
        - Oklahoma
        - Oregon
        - Pennsylvania
        - Rhode Island
        - South Carolina
        - South Dakota
        - Tennessee
        - Texas
        - Utah
        - Vermont
        - Virginia
        - Washington
        - West Virginia
        - Wisconsin
        - Wyoming
    validations:
      required: true

  - type: input
    id: official_website
    attributes:
      label: Official settlement website
      description: "The main official URL you want users to click."
      placeholder: "https://www.example-settlement.com/"
    validations:
      required: true

  - type: input
    id: hero_image
    attributes:
      label: "Hero image URL (optional)"
      description: "Leave blank if you don’t have one."
      placeholder: "https://eosguidehub.com/assets/articles/your-image.jpg"
    validations:
      required: false

  - type: input
    id: hero_credit
    attributes:
      label: "Hero image credit (optional)"
      placeholder: "Photo: Example Source"
    validations:
      required: false

  - type: input
    id: deadline
    attributes:
      label: "Claim deadline (optional)"
      placeholder: "April 10, 2026"
    validations:
      required: false

  - type: input
    id: optout_deadline
    attributes:
      label: "Opt-out deadline (optional)"
      placeholder: "March 1, 2026"
    validations:
      required: false

  - type: input
    id: hearing_date
    attributes:
      label: "Final approval hearing (optional)"
      placeholder: "May 12, 2026"
    validations:
      required: false

  - type: input
    id: settlement_amount
    attributes:
      label: "Total fund (optional)"
      placeholder: "$10,000,000"
    validations:
      required: false

  - type: input
    id: max_payment
    attributes:
      label: "Max payment per person (optional)"
      placeholder: "Up to $5,000"
    validations:
      required: false

  - type: input
    id: nodoc_payment
    attributes:
      label: "No-doc amount (optional)"
      placeholder: "$25 (no documentation)"
    validations:
      required: false

  - type: input
    id: ca_payment
    attributes:
      label: "California-only amount (optional)"
      placeholder: "$100 (CA residents)"
    validations:
      required: false

  - type: input
    id: credit_monitoring
    attributes:
      label: "Credit monitoring (optional)"
      placeholder: "2 years of credit monitoring"
    validations:
      required: false

  - type: textarea
    id: article_body
    attributes:
      label: "Main article body (optional)"
      description: "Write in short sections. Use headings if you want."
      placeholder: |
        ## What happened
        ...

        ## Who may qualify
        ...
    validations:
      required: false

  - type: textarea
    id: eligibility
    attributes:
      label: "Eligibility checklist (optional)"
      description: "One item per line."
      placeholder: |
        Received a notice OR meet the criteria on the official site
        Lived in the U.S. during the class period
    validations:
      required: false

  - type: textarea
    id: how_to_file
    attributes:
      label: "How to file (steps, optional)"
      description: "One step per line."
      placeholder: |
        Go to the official site
        Click “Submit Claim”
        Complete the form and submit
    validations:
      required: false

  - type: textarea
    id: faqs
    attributes:
      label: "FAQs (optional)"
      description: "Format like 'Q:' then 'A:' (repeat)."
      placeholder: |
        Q: Who qualifies?
        A: ...

        Q: What proof do I need?
        A: ...
    validations:
      required: false

  - type: input
    id: admin_phone
    attributes:
      label: "Administrator phone (optional)"
      placeholder: "Phone: 1-800-555-1234"
    validations:
      required: false

  - type: input
    id: admin_email
    attributes:
      label: "Administrator email (optional)"
      placeholder: "Email: info@example-settlement.com"
    validations:
      required: false

  - type: input
    id: attorney_fees
    attributes:
      label: "Attorney fees (optional)"
      placeholder: "Up to $X"
    validations:
      required: false

  - type: input
    id: service_awards
    attributes:
      label: "Service awards (optional)"
      placeholder: "Up to $X"
    validations:
      required: false

  - type: dropdown
    id: monetization
    attributes:
      label: Monetization block
      description: "Leave Off for now unless you want it."
      options:
        - Off
        - On
    validations:
      required: false
