name: New Article
description: Create a new opportunity guide for eosguidehub.com
title: "[Article] "
labels: ["article"]

body:
  - type: input
    id: title
    attributes:
      label: Article title
      description: "Headline shown at the top of the article."
      placeholder: "Example: Brand X Settlement – File by April 10, 2026"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: URL slug
      description: "Lowercase + hyphens. Example: brand-x-settlement-2026"
      placeholder: "brand-x-settlement-2026"
    validations:
      required: true

  - type: textarea
    id: blurb
    attributes:
      label: Short blurb (used on listing page + near top of article)
      description: "1–2 sentences. This becomes your meta description too."
      placeholder: "Eligible people may receive benefits if they... Deadline is..."
    validations:
      required: true

  - type: input
    id: last_updated
    attributes:
      label: Last updated
      placeholder: "February 20, 2026"
    validations:
      required: true

  - type: textarea
    id: eligible_states
    attributes:
      label: Eligible states / location
      description: "Type 'Nationwide' or list full state names separated by commas."
      placeholder: "Nationwide\n\nor\n\nCalifornia, Illinois, New York"
    validations:
      required: true

  - type: input
    id: official_website
    attributes:
      label: Official website
      description: "Primary official URL where users file / apply / check status."
      placeholder: "https://www.example-settlement.com/"
    validations:
      required: true

  - type: input
    id: claim_form_url
    attributes:
      label: Claim form URL (optional)
      placeholder: "https://www.example-settlement.com/submit-claim"
    validations:
      required: false

  - type: input
    id: important_dates_url
    attributes:
      label: Important dates URL (optional)
      placeholder: "https://www.example-settlement.com/important-dates"
    validations:
      required: false

  - type: input
    id: faqs_url
    attributes:
      label: FAQs URL (optional)
      placeholder: "https://www.example-settlement.com/faq"
    validations:
      required: false

  - type: input
    id: documents_url
    attributes:
      label: Documents URL (optional)
      placeholder: "https://www.example-settlement.com/documents"
    validations:
      required: false

  - type: input
    id: hero_image
    attributes:
      label: Hero image URL (optional)
      description: "Leave blank if you don’t have one."
      placeholder: "https://eosguidehub.com/assets/articles/example.jpg"
    validations:
      required: false

  - type: input
    id: hero_credit
    attributes:
      label: Hero image credit (optional)
      placeholder: "Photo credit: Example Source"
    validations:
      required: false

  - type: textarea
    id: what_happened
    attributes:
      label: What happened (optional)
      description: "Short bullets or a short paragraph. Keep it simple."
      placeholder: |
        - What the case is about
        - What happened (plain language)
        - Who it affects
    validations:
      required: false

  - type: textarea
    id: benefit_summary
    attributes:
      label: Benefit summary (optional)
      description: "One short line for 'what you can get'. Used in At a glance if filled."
      placeholder: "Cash payments, reimbursement, or other benefits may be available."
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits list (optional)
      description: "One per line. Format: Label | Value | Notes (notes optional)"
      placeholder: |
        Cash payment | Up to $5,000 | Amount depends on proof
        Reimbursement | Up to $250 | For out-of-pocket expenses
        Credit monitoring | 2 years | If offered
    validations:
      required: false

  - type: input
    id: deadline
    attributes:
      label: Main deadline (optional)
      description: "Claim deadline, submit-by date, or last day to act."
      placeholder: "April 10, 2026"
    validations:
      required: false

  - type: input
    id: optout_deadline
    attributes:
      label: Opt-out deadline (optional)
      placeholder: "March 1, 2026"
    validations:
      required: false

  - type: input
    id: objection_deadline
    attributes:
      label: Objection deadline (optional)
      placeholder: "March 1, 2026"
    validations:
      required: false

  - type: input
    id: hearing_date
    attributes:
      label: Final approval hearing (optional)
      placeholder: "May 12, 2026"
    validations:
      required: false

  - type: textarea
    id: eligibility
    attributes:
      label: Who may qualify (optional checklist)
      description: "One item per line."
      placeholder: |
        Received a notice OR meet criteria on the official site
        Purchased / used the product during the class period
        Lived in the eligible location(s)
    validations:
      required: false

  - type: textarea
    id: class_period
    attributes:
      label: Class period (optional)
      description: "If there is a date range, add it here."
      placeholder: "January 1, 2021 through December 31, 2023"
    validations:
      required: false

  - type: textarea
    id: how_to_file
    attributes:
      label: How to file (optional steps)
      description: "One step per line."
      placeholder: |
        Go to the official website
        Click 'Submit Claim'
        Enter your info and submit
    validations:
      required: false

  - type: textarea
    id: proof_required
    attributes:
      label: Proof required (optional)
      description: "What documentation is needed, if any. One item per line."
      placeholder: |
        Receipt, invoice, or order confirmation (if available)
        Proof of payment (optional)
        Unique ID from notice (if required)
    validations:
      required: false

  - type: textarea
    id: payment_timing
    attributes:
      label: Payment timing / method (optional)
      description: "When and how people get paid (if known)."
      placeholder: "Payments may be sent after final approval by check, ACH, PayPal, or Venmo (varies)."
    validations:
      required: false

  - type: input
    id: admin_phone
    attributes:
      label: Administrator phone (optional)
      placeholder: "1-800-555-1234"
    validations:
      required: false

  - type: input
    id: admin_email
    attributes:
      label: Administrator email (optional)
      placeholder: "info@example-settlement.com"
    validations:
      required: false

  - type: textarea
    id: admin_address
    attributes:
      label: Administrator mailing address (optional)
      placeholder: "Settlement Administrator, P.O. Box 1234, City, ST 12345"
    validations:
      required: false

  - type: textarea
    id: extra_details
    attributes:
      label: Extra details (optional)
      description: "Anything unique: automatic refunds, unique ID required, special groups, warnings, etc."
      placeholder: |
        - Some people may not need to file if refunds are automatic
        - Watch for scams: use official site only
    validations:
      required: false

  - type: textarea
    id: faqs
    attributes:
      label: FAQs (optional)
      description: "Format like Q: ... then A: ... (repeat)."
      placeholder: |
        Q: Who qualifies?
        A: ...

        Q: What proof is required?
        A: ...
    validations:
      required: false
